package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA



/**
 * DatPryInd generated by hbm2java
 */
public class DatPryInd  implements java.io.Serializable {


     private Integer id;
     private PryPryInd pryPryInd;
     private VarPryInd varPryInd;
     private String val;

    public DatPryInd() {
    }

    public DatPryInd(PryPryInd pryPryInd, VarPryInd varPryInd, String val) {
       this.pryPryInd = pryPryInd;
       this.varPryInd = varPryInd;
       this.val = val;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PryPryInd getPryPryInd() {
        return this.pryPryInd;
    }
    
    public void setPryPryInd(PryPryInd pryPryInd) {
        this.pryPryInd = pryPryInd;
    }
    public VarPryInd getVarPryInd() {
        return this.varPryInd;
    }
    
    public void setVarPryInd(VarPryInd varPryInd) {
        this.varPryInd = varPryInd;
    }
    public String getVal() {
        return this.val;
    }
    
    public void setVal(String val) {
        this.val = val;
    }




}


