package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * EstPryInd generated by hbm2java
 */
public class EstPryInd  implements java.io.Serializable {


     private Integer id;
     private String desEstPry;
     private Set pryPryInds = new HashSet(0);

    public EstPryInd() {
    }

    public EstPryInd(String desEstPry, Set pryPryInds) {
       this.desEstPry = desEstPry;
       this.pryPryInds = pryPryInds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDesEstPry() {
        return this.desEstPry;
    }
    
    public void setDesEstPry(String desEstPry) {
        this.desEstPry = desEstPry;
    }
    public Set getPryPryInds() {
        return this.pryPryInds;
    }
    
    public void setPryPryInds(Set pryPryInds) {
        this.pryPryInds = pryPryInds;
    }




}


