package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA


import java.util.Calendar;

/**
 * EtpMatPryInd generated by hbm2java
 */
public class EtpMatPryInd  implements java.io.Serializable {


     private Integer id;
     private TipMatPryInd tipMatPryInd;
     private PryPryInd pryPryInd;
     private Integer numEta;
     private Calendar fch;
     private String val;

    public EtpMatPryInd() {
    }

    public EtpMatPryInd(TipMatPryInd tipMatPryInd, PryPryInd pryPryInd, Integer numEta, Calendar fch, String val) {
       this.tipMatPryInd = tipMatPryInd;
       this.pryPryInd = pryPryInd;
       this.numEta = numEta;
       this.fch = fch;
       this.val = val;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TipMatPryInd getTipMatPryInd() {
        return this.tipMatPryInd;
    }
    
    public void setTipMatPryInd(TipMatPryInd tipMatPryInd) {
        this.tipMatPryInd = tipMatPryInd;
    }
    public PryPryInd getPryPryInd() {
        return this.pryPryInd;
    }
    
    public void setPryPryInd(PryPryInd pryPryInd) {
        this.pryPryInd = pryPryInd;
    }
    public Integer getNumEta() {
        return this.numEta;
    }
    
    public void setNumEta(Integer numEta) {
        this.numEta = numEta;
    }
    public Calendar getFch() {
        return this.fch;
    }
    
    public void setFch(Calendar fch) {
        this.fch = fch;
    }
    public String getVal() {
        return this.val;
    }
    
    public void setVal(String val) {
        this.val = val;
    }




}


