package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA



/**
 * EtpPryInd generated by hbm2java
 */
public class EtpPryInd  implements java.io.Serializable {


     private Integer id;
     private PryPryInd pryPryInd;
     private VarPryInd varPryInd;
     private Integer numEta;
     private String val;

    public EtpPryInd() {
    }

    public EtpPryInd(PryPryInd pryPryInd, VarPryInd varPryInd, Integer numEta, String val) {
       this.pryPryInd = pryPryInd;
       this.varPryInd = varPryInd;
       this.numEta = numEta;
       this.val = val;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PryPryInd getPryPryInd() {
        return this.pryPryInd;
    }
    
    public void setPryPryInd(PryPryInd pryPryInd) {
        this.pryPryInd = pryPryInd;
    }
    public VarPryInd getVarPryInd() {
        return this.varPryInd;
    }
    
    public void setVarPryInd(VarPryInd varPryInd) {
        this.varPryInd = varPryInd;
    }
    public Integer getNumEta() {
        return this.numEta;
    }
    
    public void setNumEta(Integer numEta) {
        this.numEta = numEta;
    }
    public String getVal() {
        return this.val;
    }
    
    public void setVal(String val) {
        this.val = val;
    }




}


