package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA


import java.util.Calendar;

/**
 * MatPryInd generated by hbm2java
 */
public class MatPryInd  implements java.io.Serializable {


     private Integer id;
     private TipMatPryInd tipMatPryInd;
     private PryPryInd pryPryInd;
     private Calendar fch;
     private String val;

    public MatPryInd() {
    }

    public MatPryInd(TipMatPryInd tipMatPryInd, PryPryInd pryPryInd, Calendar fch, String val) {
       this.tipMatPryInd = tipMatPryInd;
       this.pryPryInd = pryPryInd;
       this.fch = fch;
       this.val = val;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TipMatPryInd getTipMatPryInd() {
        return this.tipMatPryInd;
    }
    
    public void setTipMatPryInd(TipMatPryInd tipMatPryInd) {
        this.tipMatPryInd = tipMatPryInd;
    }
    public PryPryInd getPryPryInd() {
        return this.pryPryInd;
    }
    
    public void setPryPryInd(PryPryInd pryPryInd) {
        this.pryPryInd = pryPryInd;
    }
    public Calendar getFch() {
        return this.fch;
    }
    
    public void setFch(Calendar fch) {
        this.fch = fch;
    }
    public String getVal() {
        return this.val;
    }
    
    public void setVal(String val) {
        this.val = val;
    }




}


