package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA


import java.util.Calendar;

/**
 * MdlPryInd generated by hbm2java
 */
public class MdlPryInd  implements java.io.Serializable {


     private Integer id;
     private PryPryInd pryPryInd;
     private Usu usu;
     private String nomMdl;
     private Calendar fec;

    public MdlPryInd() {
    }

    public MdlPryInd(PryPryInd pryPryInd, Usu usu, String nomMdl, Calendar fec) {
       this.pryPryInd = pryPryInd;
       this.usu = usu;
       this.nomMdl = nomMdl;
       this.fec = fec;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PryPryInd getPryPryInd() {
        return this.pryPryInd;
    }
    
    public void setPryPryInd(PryPryInd pryPryInd) {
        this.pryPryInd = pryPryInd;
    }
    public Usu getUsu() {
        return this.usu;
    }
    
    public void setUsu(Usu usu) {
        this.usu = usu;
    }
    public String getNomMdl() {
        return this.nomMdl;
    }
    
    public void setNomMdl(String nomMdl) {
        this.nomMdl = nomMdl;
    }
    public Calendar getFec() {
        return this.fec;
    }
    
    public void setFec(Calendar fec) {
        this.fec = fec;
    }




}


