package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA


import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/**
 * PryPryInd generated by hbm2java
 */
public class PryPryInd  implements java.io.Serializable {


     private Integer id;
     private EstPryInd estPryInd;
     private String nomPry;
     private Calendar fch;
     private Set etpPryInds = new HashSet(0);
     private Set mdlPryInds = new HashSet(0);
     private Set datPryInds = new HashSet(0);
     private Set matPryInds = new HashSet(0);
     private Set usuPryPryInds = new HashSet(0);
     private Set etpMatPryInds = new HashSet(0);

    public PryPryInd() {
    }

    public PryPryInd(EstPryInd estPryInd, String nomPry, Calendar fch, Set etpPryInds, Set mdlPryInds, Set datPryInds, Set matPryInds, Set usuPryPryInds, Set etpMatPryInds) {
       this.estPryInd = estPryInd;
       this.nomPry = nomPry;
       this.fch = fch;
       this.etpPryInds = etpPryInds;
       this.mdlPryInds = mdlPryInds;
       this.datPryInds = datPryInds;
       this.matPryInds = matPryInds;
       this.usuPryPryInds = usuPryPryInds;
       this.etpMatPryInds = etpMatPryInds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EstPryInd getEstPryInd() {
        return this.estPryInd;
    }
    
    public void setEstPryInd(EstPryInd estPryInd) {
        this.estPryInd = estPryInd;
    }
    public String getNomPry() {
        return this.nomPry;
    }
    
    public void setNomPry(String nomPry) {
        this.nomPry = nomPry;
    }
    public Calendar getFch() {
        return this.fch;
    }
    
    public void setFch(Calendar fch) {
        this.fch = fch;
    }
    public Set getEtpPryInds() {
        return this.etpPryInds;
    }
    
    public void setEtpPryInds(Set etpPryInds) {
        this.etpPryInds = etpPryInds;
    }
    public Set getMdlPryInds() {
        return this.mdlPryInds;
    }
    
    public void setMdlPryInds(Set mdlPryInds) {
        this.mdlPryInds = mdlPryInds;
    }
    public Set getDatPryInds() {
        return this.datPryInds;
    }
    
    public void setDatPryInds(Set datPryInds) {
        this.datPryInds = datPryInds;
    }
    public Set getMatPryInds() {
        return this.matPryInds;
    }
    
    public void setMatPryInds(Set matPryInds) {
        this.matPryInds = matPryInds;
    }
    public Set getUsuPryPryInds() {
        return this.usuPryPryInds;
    }
    
    public void setUsuPryPryInds(Set usuPryPryInds) {
        this.usuPryPryInds = usuPryPryInds;
    }
    public Set getEtpMatPryInds() {
        return this.etpMatPryInds;
    }
    
    public void setEtpMatPryInds(Set etpMatPryInds) {
        this.etpMatPryInds = etpMatPryInds;
    }




}


