package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA



/**
 * RelMdlVeh generated by hbm2java
 */
public class RelMdlVeh  implements java.io.Serializable {


     private Integer id;
     private MdlVeh mdlVeh;
     private PryVeh pryVeh;

    public RelMdlVeh() {
    }

    public RelMdlVeh(MdlVeh mdlVeh, PryVeh pryVeh) {
       this.mdlVeh = mdlVeh;
       this.pryVeh = pryVeh;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MdlVeh getMdlVeh() {
        return this.mdlVeh;
    }
    
    public void setMdlVeh(MdlVeh mdlVeh) {
        this.mdlVeh = mdlVeh;
    }
    public PryVeh getPryVeh() {
        return this.pryVeh;
    }
    
    public void setPryVeh(PryVeh pryVeh) {
        this.pryVeh = pryVeh;
    }




}


