package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA


import java.util.Calendar;

/**
 * RepVeh generated by hbm2java
 */
public class RepVeh  implements java.io.Serializable {


     private Integer id;
     private Integer mdlVeh;
     private Calendar fec;

    public RepVeh() {
    }

    public RepVeh(Integer mdlVeh, Calendar fec) {
       this.mdlVeh = mdlVeh;
       this.fec = fec;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getMdlVeh() {
        return this.mdlVeh;
    }
    
    public void setMdlVeh(Integer mdlVeh) {
        this.mdlVeh = mdlVeh;
    }
    public Calendar getFec() {
        return this.fec;
    }
    
    public void setFec(Calendar fec) {
        this.fec = fec;
    }




}


