package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipMatPryInd generated by hbm2java
 */
public class TipMatPryInd  implements java.io.Serializable {


     private Integer id;
     private String desTipMat;
     private Set matPryInds = new HashSet(0);
     private Set etpMatPryInds = new HashSet(0);

    public TipMatPryInd() {
    }

    public TipMatPryInd(String desTipMat, Set matPryInds, Set etpMatPryInds) {
       this.desTipMat = desTipMat;
       this.matPryInds = matPryInds;
       this.etpMatPryInds = etpMatPryInds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDesTipMat() {
        return this.desTipMat;
    }
    
    public void setDesTipMat(String desTipMat) {
        this.desTipMat = desTipMat;
    }
    public Set getMatPryInds() {
        return this.matPryInds;
    }
    
    public void setMatPryInds(Set matPryInds) {
        this.matPryInds = matPryInds;
    }
    public Set getEtpMatPryInds() {
        return this.etpMatPryInds;
    }
    
    public void setEtpMatPryInds(Set etpMatPryInds) {
        this.etpMatPryInds = etpMatPryInds;
    }




}


