package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipMapCalVeh generated by hbm2java
 */
public class TipMapCalVeh  implements java.io.Serializable {


     private Integer id;
     private String desLar;
     private Set mapCalVehs = new HashSet(0);

    public TipMapCalVeh() {
    }

    public TipMapCalVeh(String desLar, Set mapCalVehs) {
       this.desLar = desLar;
       this.mapCalVehs = mapCalVehs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDesLar() {
        return this.desLar;
    }
    
    public void setDesLar(String desLar) {
        this.desLar = desLar;
    }
    public Set getMapCalVehs() {
        return this.mapCalVehs;
    }
    
    public void setMapCalVehs(Set mapCalVehs) {
        this.mapCalVehs = mapCalVehs;
    }




}


