package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipMatVeh generated by hbm2java
 */
public class TipMatVeh  implements java.io.Serializable {


     private Integer id;
     private String desTipMat;
     private Set matVehs = new HashSet(0);

    public TipMatVeh() {
    }

    public TipMatVeh(String desTipMat, Set matVehs) {
       this.desTipMat = desTipMat;
       this.matVehs = matVehs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDesTipMat() {
        return this.desTipMat;
    }
    
    public void setDesTipMat(String desTipMat) {
        this.desTipMat = desTipMat;
    }
    public Set getMatVehs() {
        return this.matVehs;
    }
    
    public void setMatVehs(Set matVehs) {
        this.matVehs = matVehs;
    }




}


