package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipUsu generated by hbm2java
 */
public class TipUsu  implements java.io.Serializable {


     private Integer id;
     private String desTipUsu;
     private Set usus = new HashSet(0);

    public TipUsu() {
    }

    public TipUsu(String desTipUsu, Set usus) {
       this.desTipUsu = desTipUsu;
       this.usus = usus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDesTipUsu() {
        return this.desTipUsu;
    }
    
    public void setDesTipUsu(String desTipUsu) {
        this.desTipUsu = desTipUsu;
    }
    public Set getUsus() {
        return this.usus;
    }
    
    public void setUsus(Set usus) {
        this.usus = usus;
    }




}


