package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA



/**
 * UsuMdlVeh generated by hbm2java
 */
public class UsuMdlVeh  implements java.io.Serializable {


     private Integer id;
     private MdlVeh mdlVeh;
     private Usu usu;
     private EstPryVeh estPryVeh;

    public UsuMdlVeh() {
    }

    public UsuMdlVeh(MdlVeh mdlVeh, Usu usu, EstPryVeh estPryVeh) {
       this.mdlVeh = mdlVeh;
       this.usu = usu;
       this.estPryVeh = estPryVeh;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MdlVeh getMdlVeh() {
        return this.mdlVeh;
    }
    
    public void setMdlVeh(MdlVeh mdlVeh) {
        this.mdlVeh = mdlVeh;
    }
    public Usu getUsu() {
        return this.usu;
    }
    
    public void setUsu(Usu usu) {
        this.usu = usu;
    }
    public EstPryVeh getEstPryVeh() {
        return this.estPryVeh;
    }
    
    public void setEstPryVeh(EstPryVeh estPryVeh) {
        this.estPryVeh = estPryVeh;
    }




}


