package pojos;
// Generated 29-mar-2012 18:27:14 by Hibernate Tools 3.2.1.GA



/**
 * UsuPryVeh generated by hbm2java
 */
public class UsuPryVeh  implements java.io.Serializable {


     private Integer id;
     private Usu usu;
     private PryVeh pryVeh;
     private EstPryVeh estPryVeh;

    public UsuPryVeh() {
    }

    public UsuPryVeh(Usu usu, PryVeh pryVeh, EstPryVeh estPryVeh) {
       this.usu = usu;
       this.pryVeh = pryVeh;
       this.estPryVeh = estPryVeh;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usu getUsu() {
        return this.usu;
    }
    
    public void setUsu(Usu usu) {
        this.usu = usu;
    }
    public PryVeh getPryVeh() {
        return this.pryVeh;
    }
    
    public void setPryVeh(PryVeh pryVeh) {
        this.pryVeh = pryVeh;
    }
    public EstPryVeh getEstPryVeh() {
        return this.estPryVeh;
    }
    
    public void setEstPryVeh(EstPryVeh estPryVeh) {
        this.estPryVeh = estPryVeh;
    }




}


